# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d856a42d26231c1ecdbe548705d3ed968310f8d83ea0b4db7f40ec8b935946ba9af97bec8063b0c6d4944c2b5617ccb7bcd13b7049290aba6460e3be15a9af6

test:
  secret_key_base: 7172a8291989dae5fe8da7f558e073080ec737864a93b4abaa16e700c0cca5b3d43df14a9b87c57d7168f2903a0bf71cd4ffd142cc33c88967d14fa78ba91442

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
